server:
  port: 80
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 12345
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  session:
    store-type: redis
  application:
    name: alageek-crowd-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: alageek-crowd-auth
      path: /**
    crowd-project:
      service-id: alageek-crowd-project
      path: /project/**
    crowd-order:
      service-id: alageek-crowd-order
      path: /order/**
    crowd-pay:
      service-id: alageek-crowd-pay
      path: /pay/**