#aliyun:
#  oss:
#    access-key-id:
#    access-key-secret:
#    bucket-domain: http://alageek-test.oss-cn-shanghai.aliyuncs.com
#    bucket-name: alageek-test
#    end-point: http://oss-cn-shanghai.aliyuncs.com
server:
  port: 5000
spring:
  application:
    name: alageek-crowd-project
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 12345
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/